### ISSUE TITLE
Is it possible to disable shortcuts

### ISSUE THREAD

**Issue by ghost** [nozzle/nzTour#11]
I have some functionality in the "after" of some of my steps. I would like the user not to be able to get back to that step without restarting. Is this possible, Also on a side note can the previous button be disabled? At the moment I am simply hiding it.

**Comment by tannerlinsley** [comment]
To answer both questions. There isn't a way to disable the back
functionality yet. It could easily be done. Once again if you would like to
submit those changes, feel free to PR

**Comment by tannerlinsley** [comment]
If not I'll have some time in the next week or two to implement some of
these new features being requested.

**Comment by ghost** [comment]
Ok. I might have a look over the weekend at those issues and if I come up with anything I will make a PR. Great work so far by the way!

**Comment by tannerlinsley** [comment]
Thanks!  I'd like it to become more widely used and contributed to.  Please
share!

**Comment by Steve-Mc** [comment]
Hey you can close this issue if you want. @BannedForLife is my personal account. I forked and contributed on my work account.
