### ISSUE TITLE
Working with Modals

### ISSUE THREAD

**Issue by rammoozz** [nozzle/nzTour#15]
Has anyone experienced issues with scrolling and modals?

Update - works after setting scrollBox: '.modal', but the last step won't scroll to the bottom of the modal. Any attempt to scroll down forces the user back up.

Update - Uncaught ReferenceError: innerContent is not define

I fixed by using the following (it's hacky but I need to finish implementing this)
   before: function(){
            var d = $q.defer();
            $(".modal").scrollTop(0);
            d.resolve(); // or d.reject()
            return d.promise
        }

**Comment by rammoozz** [comment]
This is becoming an increasing problem with very long modals :-1:

**Comment by lebolo** [comment]
Can you create a plunker to help debug?

Also, the `innerContent` error was fixed in #13, but I don't think a new version has been pushed to bower.

**Comment by rammoozz** [comment]
Here is a codepen I threw together quickly, I was not able to get the tour to start however. 

http://codepen.io/dnwebdev/pen/rOxXQP

In my original code, we are using Angular Bootstrap UI  Modals : https://angular-ui.github.io/bootstrap/#/modal

Upon clicking 'next' in the tour, the modal scrolls down and then scrolls back to the middle, any attempt to scroll down causes jitter.

**Comment by lebolo** [comment]
I forked your codepen and it seems to work okay for me. I added the nz-tour js and css files.

http://codepen.io/anon/pen/bVpbwK

You forgot to add `'nzTour'` to the controller definition

``` javascript
myApp.controller('myController', [
  '$scope',
  'nzTour', // Added this part
  function($scope, nzTour) {
    ...
```

I then added more text to make the modal extra long, set `scrollBox: '.modal'` and it correctly scrolls down to the bottom (I added steps and changed the ids).

**Comment by rammoozz** [comment]
Could this be an issue with using the Bootstrap Angular UI Modals with UI Router?

**Comment by lebolo** [comment]
It might be, I've never used UI Router, so don't know what the HTML looks like it that case. It's hard to debug without seeing the code you're running. I assume it's too difficult to recreate your exact environment/code on plunker or codepen though?

**Comment by rammoozz** [comment]
Yes it is not possible to recreate it through a snippet, it has UI router / bootstrap UI
Thanks for looking into it though.
