### ISSUE TITLE
Icon on a header-bar is not recignized

### ISSUE THREAD

**Issue by soniyj** [nozzle/nzTour#17]
Hello, I was testing your tour and I found it amazing. I'm testing now with Ionic and the menu but while works perfectly with other icons, if I try to add a icon that is on the header bar, the tour goes on the top but doesn't get the icone neither on the left nor on the right.

Any ideas?

**Comment by tannerlinsley** [comment]
Hmm, I haven't tested it with this yet.  I'll try and take a look and let
you know what I find out.

**Comment by soniyj** [comment]
OK it recognises that the icon is on the top because the focus moves up, but doesn't get the icon, would be great if you could have a look also for the footer, I didn't test, I will do and let you know. Thanks

**Comment by soniyj** [comment]
I made the same test but focusing the tour on the footer, it recognises the icons but the box showing the text and the buttons goes outside the view (shown below the icon), should be design the box on top of the icon.

**Comment by tannerlinsley** [comment]
I'll be working on this possibly in version 2.0. It has to do with the box model of the icons in ionic. Closing for now.

**Comment by tannerlinsley** [comment]
I'll be working on this possibly in version 2.0. It has to do with the box model of the icons in ionic. Closing for now.
