### ISSUE TITLE
direction is returning 'undefined' instead of -1 or 1

### ISSUE THREAD

**Issue by santosh532** [nozzle/nzTour#26]
Hi,

I was trying to use one of the in built functionality to track the movement of tooltip (forward or backward) using:

```
before: function(direction){
                console.log("direction",direction); // returns undefined
                if (direction === -1) {
                      console.log('coming from next step');
                } else if (direction === 1) {
                      console.log('coming from previous step');
                } else {
                      console.log('started at this step');
                }
                var d = $q.defer();
                // Do something amazing
                d.resolve(); // or d.reject()
                return d.promise;
            }
```

but the direction is always _undefined_ 

Can you please help me out with this?

**Comment by lebolo** [comment]
@santosh532 is this still a problem? If so, can you create a plunker?

I created a [plunker](http://plnkr.co/edit/VW8MpBOd8Ap0Iv3jjr78?p=preview) based on the demo site using v1.1.0 of the tour.

If you open up your console and go move to step 7, you'll see it print out the direction.

**Comment by lebolo** [comment]
Closing issue due to lack of feedback, feel free to reopen if the problem still persists.
