### ISSUE TITLE
how to prevent click on highlight eliment

### ISSUE THREAD

**Issue by sannysinghs** [nozzle/nzTour#27]
I was expecting "disableInteraction: true" might prevent the click on targeted element. But it doesn't seem to work for me. Is there a way to explicitly disable click event on it ? Thanks .

**Comment by lebolo** [comment]
Hi @sannysinghs, are you still having problems with `disableInteraction`? If so, can you create a plunker?

I created a [plunker](https://plnkr.co/edit/l7GYXN5WDp6Z8nyUVPMN?p=preview) based on the demo site using v1.1.0. When `disableInteraction` is enabled, I can't click on the _Start Tour_ button during step 4.

**Comment by lebolo** [comment]
Closing issue due to lack of feedback, feel free to reopen if the problem still persists.
