### ISSUE TITLE
innerContent is not defined

### ISSUE THREAD

**Issue by mlandry360** [nozzle/nzTour#32]
Hi,

I'm getting innerContent is not defined when I scroll a step box with a lot of text inside.
The error is in onBoxScroll function at line 472

innerContent should be accessible from els variable, this code fix the issue :
`if (!up && (els.innerContent.height() - els.content.height() == scrollTop)) {
                        return prevent(e);
                    }`

**Comment by lebolo** [comment]
Hi @mlandry360, are you still seeing this problem? If so, can you create a plunker to show the problem?

I created a [plunker](https://plnkr.co/edit/v3325zvotUi9G1RgIL5p?p=preview) using v1.1.0 based on the demo site. I added a lot of text to step 2 and I scroll without any issues.

**Comment by lebolo** [comment]
Oops, this problem was actually [fixed by me](https://github.com/nozzle/nzTour/pull/13) some time ago :innocent:. Updating to the latest version (v1.1.0) should fix things.

**Comment by mlandry360** [comment]
Great thanks! I updated to v1.1.0 and no more scroll error.
