### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by chedched** [nozzle/nzTour#34]
Thanks a lot for this great plugin!
I just wonder if it's possible to use internationalization/translation with it (something like https://github.com/angular-translate/angular-translate for instance)? I'm unfortunately not an Angular pro yet, but I think the reason why it currently doesn't work is because of the $compile():

`var compiledHtml = $compile(stepHtml)($scope);`

Or is there any way already how to use translation with nzTour?

(Could be related to https://github.com/nozzle/nzTour/issues/28 - "I would first explore making it so directives compile inside the content")

**Comment by tannerlinsley** [comment]
Right now there isn't any directly supported way to support i18n, but I'm sure you could make it work with some tweaking. All $compile is doing is simply running the angular directive parser on your text, and also attaching the scope to it.  so any i18n functionality, so long as it uses a directive, should work.  I have not yet tried any of it on my own.

**Comment by chedched** [comment]
Thanks for your answer. As I managed get it work on jsfiddle (http://jsfiddle.net/Lvc0u55v/6282/) it appears I had some typo in my code.
