### ISSUE TITLE
Firefox autoscroll is not working

### ISSUE THREAD

**Issue by sumbon** [nozzle/nzTour#38]
Hi,  The tour is working on Chrome and IE. However only on firefox autoscrolling doesn't work when the next section in tour points to a place where we need to scroll.

**Comment by lebolo** [comment]
Which version of nzTour are you using? Can you mimic the behavior in a Plunkr (you can use [this](http://plnkr.co/edit/EujJVStquAf9RAHqcyC2?p=preview) as a template)?

**Comment by sumbon** [comment]
We were able to resolve this by removing scrollbox property from config.
