### ISSUE TITLE
Disabling Tagged Elements During Tour

### ISSUE THREAD

**Issue by nicolairobles** [nozzle/nzTour#42]
Is there a way to disable the tagged elements, if applicable, while the tour is happening?

I run into the issue that one of my tour steps is a button and people are inclined to press the button during the tour, instead of next. I'd like to disable the button.

**Comment by lebolo** [comment]
Hi @nicolairobles, there's a `disableInteraction` parameter you can set on the tour config.

> disableInteraction: false, // Disable interaction with the highlighted elements

Is that what you mean?

**Comment by nicolairobles** [comment]
Yes, it is. Thanks!
