### ISSUE TITLE
Change scrollBox Config when nzTour Active?

### ISSUE THREAD

**Issue by farizsofyan** [nozzle/nzTour#43]
Hello, everyone.

First, i thank you for this great Angular Tour plugin.

Currently, i am developing tour feature using this plugin. I want to ask, is there a way to change 'scrollBox' configuration when the plugin is active?

Thank you

**Comment by lebolo** [comment]
Hi @farizsofyan. From a quick look at the source, I'm not seeing any way of modifying `scrollBox` while the tour is active. If you're interested in modifying the source code yourself, you may want to look at [this line](https://github.com/nozzle/nzTour/blob/master/src/nz-tour.js#L302) and try exposing the variable `els` or `els.scroll` to the service.

**Comment by farizsofyan** [comment]
yeah, it seems i have to modify the source
thanks lebolo for the help
