### ISSUE TITLE
Doesn't work with scrolling in Chrome

### ISSUE THREAD

**Issue by Overv** [nozzle/nzTour#47]
When I press "Start Demo" on the website (http://nozzle.github.io/nzTour/) and start scrolling, the overlay stays in the same place:

![](https://i.imgur.com/dRqvC8j.png)

**Comment by lebolo** [comment]
I can't reproduce this. I'm using Google Chrome 61.0.3163.100 on Windows 7. Maybe try opening up your Developer Tools and see if there are errors in the console?

**Comment by lebolo** [comment]
Also keep in mind that this repo is not being actively developed - check out https://github.com/tourjs/Tour instead.

**Comment by Overv** [comment]
I get the same problem with Tour and no errors in the console:

![](https://i.imgur.com/Bi76pRU.png)

Chrome version 61.0.3163.100 on Windows 10

**Comment by lebolo** [comment]
I moved this issue over to https://github.com/tourjs/tour/issues/11
