### ISSUE TITLE
elem[_addEventListener] is not a function

### ISSUE THREAD

**Issue by rammoozz** [nozzle/nzTour#7]
Hello,

I must say I am impressed with your tour! I was having problems with z-index with previous tours where this one seems to work with no issues! I am however experiencing an error in the console.

elem[_addEventListener] is not a function

This only happens when I set scrollThrough option to false. It seems to be thrown from the following lines
 if (config.mask.scrollThrough === false) {
                    window.addWheelListener(els.masks_wrap, stopMaskScroll);
                }

Also, I am using UI router in a SPA if that matters.

Thanks.

**Comment by rammoozz** [comment]
Update - Turning on scrollThrough option throws the following error

innerContent is not defined

Still working though.

Update:  This error seems to be thrown on your website also
http://nozzle.github.io/nzTour/

**Comment by rammoozz** [comment]
Could it be because I am using ' target: document.querySelector('#step1'),'

**Comment by tannerlinsley** [comment]
You don't need to query the selector yourself. Just use jquery selector
syntax.
