### ISSUE TITLE
slight flicker 

### ISSUE THREAD

**Issue by rammoozz** [nozzle/nzTour#8]
Hello,

I am seeing a white line 'flicker' when the tour starts, especially when scrolling. I see it in IE and chrome.

Edit - Also happening on the example provided

**Comment by tannerlinsley** [comment]
This is a downside to using CSS masks. A better approach would use svg or canvas overlays. Closing for now. Maybe we'll do this on version 2

**Comment by nicolairobles** [comment]
I experienced some flickers and some initially incorrect mask sizing. My work-around is to scroll by an unnoticeable amount, which triggers the browser to correct the masks.

``` javascript
 steps: [{
            target: '.tour',
            content: "blurb.",
            before: function(direction){
              var d = $q.defer();
              // SCROLL
                 window.scrollBy(0,1);
                 console.log("scrolled to fix mask ")
              d.resolve(); // or d.reject()
              return d.promise
            }
        }]
```

**Comment by tannerlinsley** [comment]
To alleviate this entirely, you could try the new tour.js here: https://github.com/tourjs/Tour.  It's a rewrite of the module to be framework agnostic and the masking is powered via a canvas element. So flickers be gone!
